INSERT INTO habilidade (habilidade_possivel) VALUES ('C');
INSERT INTO habilidade (habilidade_possivel) VALUES ('C++');
INSERT INTO habilidade (habilidade_possivel) VALUES ('C#');
INSERT INTO habilidade (habilidade_possivel) VALUES ('Java');
INSERT INTO habilidade (habilidade_possivel) VALUES ('Python');
INSERT INTO habilidade (habilidade_possivel) VALUES ('JavaScript');
INSERT INTO habilidade (habilidade_possivel) VALUES ('HTML5');
INSERT INTO habilidade (habilidade_possivel) VALUES ('CSS3');
INSERT INTO habilidade (habilidade_possivel) VALUES ('Ruby');
INSERT INTO habilidade (habilidade_possivel) VALUES ('NodeJS');
INSERT INTO habilidade (habilidade_possivel) VALUES ('Angular');
INSERT INTO habilidade (habilidade_possivel) VALUES ('AngularJS');
INSERT INTO habilidade (habilidade_possivel) VALUES ('React');
INSERT INTO habilidade (habilidade_possivel) VALUES ('TypeScript');
INSERT INTO habilidade (habilidade_possivel) VALUES ('UX Research');
INSERT INTO habilidade (habilidade_possivel) VALUES ('Product Design');
INSERT INTO habilidade (habilidade_possivel) VALUES ('UX Writing');
INSERT INTO habilidade (habilidade_possivel) VALUES ('Teste de Usabilidade');
INSERT INTO habilidade (habilidade_possivel) VALUES ('Design Thinking');
INSERT INTO habilidade (habilidade_possivel) VALUES ('Prototipagem');
INSERT INTO habilidade (habilidade_possivel) VALUES ('Interface Gráfica do Usuário (GUI)');
INSERT INTO habilidade (habilidade_possivel) VALUES ('Acessibilidade');
INSERT INTO habilidade (habilidade_possivel) VALUES ('Design Responsivo');
INSERT INTO habilidade (habilidade_possivel) VALUES ('Microinterações');